### ISSUE TITLE
[ Bug Raised ] : Copy Button on the React App Not Working on Heroku

### ISSUE THREAD

**Issue by shravan20** [shravan20/github-readme-quotes#104]
**Describe the bug**
Unable to copy the predefined URL from the UI screen

**To Reproduce**
1. Go to 'http://github-readme-quotes.herokuapp.com'
2. Click on 'COPY TEXT' button
3. Paste it else where
4. You see the text is not copied

**Expected behavior**
Upon click, copies the text content.

**Additional context**
Working properly fine on the localhost. Unable to copy in the heroku platform.

**Comment by ShubhKotnala** [comment]
Hi, 
I have taken a look into this, and it seems to be a SSL certificate problem. 
I've verified and confirmed that the browser is blocking access to clipboard due to the insecure connection.
