### ISSUE TITLE
Dark Theme for the website

### ISSUE THREAD

**Issue by shravan20** [shravan20/github-readme-quotes#120]
**Is your feature request related to a problem? Please describe.**
Implementation of the Dark Theme for the React Website for Github Readme Quotes, to get a view of how the card looks in the Dark theme of the Github API

**Comment by koskrit** [comment]
Hi Shravan, I'd like to help with this issue.
 
Since this app is using Material-UI, I could try to implement custom global themes. 
More Precisely:
- Add a ThemeProvider at Dashboard
- Import custom Global theme objects
- Add toggle theme state to Dashboard
- Append Toggle Button to Dashboard / AppBar to change theme state

Is this similar to what you've had in mind?

**Comment by shravan20** [comment]
Hi @koskrit ,

Thank you for your time!
Yes, we were looking for something similar to what you proposed. Feel free to implement your ideology and raise a PR.

Looking forward to see your PR.

**Comment by koskrit** [comment]
Update1: 

- [x] Added ThemeProvider at Dashboard
- [x] Added toggle theme state
- [x] Added Toggle Button to Dashboard / AppBar to change theme state
- [x] Tested Theme functionality with sample themes
- [ ] Create Github Dark Theme with JSS

**Comment by shravan20** [comment]
@koskrit Will Peer review the code and let you know the status.

**Comment by koskrit** [comment]
Before I do some cleanup and submit the PR, maybe you could give me some thoughts on the first draft.

Update2:
- [ ] Create Github Dark Theme with JSS
----
Theme Draft1

![ddf](https://i.imgur.com/Bt1jVy7.gif)
----
All colors are taken from the Github [color palette](https://primer.style/css/support/color-system)

Any reflections or preferences for the color choices?

**Comment by shravan20** [comment]
Hi @koskrit 
I believe the colour choices for the dark mode looks good for now. Inverted duo is fine for now!
