### ISSUE TITLE
Simple Thank You Collaborators Card on the UI

### ISSUE THREAD

**Issue by shravan20** [shravan20/github-readme-quotes#122]
**Is your feature request related to a problem? Please describe.**
Implementation of simple div card, thanking the contributors

**Describe the solution you'd like**
A simple card to applauding the contributors for their contribution as a part of the Github-Readme-Quotes Website itself. 

Feel free to propose any new alternative.

**Comment by version0chiro** [comment]
I have sent a PR with only the front end part prepared and implemented here #125 , I am unable to proceed forward on how to convert this into production build as I am new to react.js. Will be great if you can guide me through that. Here is how the card looks, More details can be found in the PR.
![image](https://user-images.githubusercontent.com/56084650/116034546-15b35b80-a681-11eb-8332-2ea98a5a0b12.png)
