### ISSUE TITLE
Implementation of Quote Card with [Background Image](https://codepen.io/governorfancypants/pen/elsDc)

### ISSUE THREAD

**Issue by shravan20** [shravan20/github-readme-quotes#123]
**Is your feature request related to a problem? Please describe.**
Implementation to have a background image instead of solid colour

**Describe the solution you'd like**
Implementation of adding a background image as optional instead of solid colour 

**Additional context**
Not just new card, but also with existing cards as well.

**Comment by Rispectech** [comment]
#124

**Comment by shravan20** [comment]
Hi @Rispectech 
I have assigned both the issues to you!
THank you so much for your time :)

**Comment by Rispectech** [comment]
sure thanks a lot @shravan20. actually, I was assigned 2 other issues on other repos so I think I won't be able to work on this for the next week or 2 most probably. so if u are fine with that then all is good.

**Comment by shravan20** [comment]
This wont be an issue. Take your time. :)

**Comment by dolmushcu** [comment]
Hey @Rispectech are you still working on it? If you don't have time i can take up this issue.

**Comment by Rispectech** [comment]
hey @dolmushcu . i just started working on the issue so i will be grateful if i can get some more time . if i am unable to solve it within the next 2 weeks , you can take the issue . 
Sorry for the inconvienve . hope you can comply with it . Thank you

**Comment by shravan20** [comment]
Hi @dolmushcu 
#124 is a different feature implementation compared to this one. Both will have different approaches. We cannot go with the same approach.

**Comment by Rispectech** [comment]
> Absolutely, i thought i should ask, if you're busy or something i thought i could be helpful. There is no inconvenience. As for the splitting issues, i guess these two issues could be solved with the same approach, so you should take up both. Sorry if my recent comment is a bit indiscreet.

if that's the case , then please go ahead with the issue because its true that i am a bit busy . Thanks for the help .
and about your comments being indiscreet, i would say it was me who was being disrespectfull since the issue has been sitting for more than a month now so your comment was completely right on the mark . so please go ahead with the issue 
again sorry for my behavior

**Comment by dolmushcu** [comment]
> Hi @dolmushcu #124 is a different feature implementation compared to this one. Both will have different approaches. We cannot go with the same approach.

Here is what i thought:
In the file where the themes being specified (src/themes/themes.js), we could pass `bg_color` values directly. I mean right now `#` character is being added automaticly assuming every value that passed is hex in the layout file. However if we let people pass quote_color, bg_color... freely, they could be able to pass gradient color and image.

EXP: bg_color: "linear-gradient(to right, #0f2027, #203a43, #2c5364)"
EXP: bg_color: "url('http://example.com/image.png')"
EXP: bg_color: "#fff"

When i mention about same approach i was talking about something like this. What do you think? Does this approach have any drawback?

**Comment by dolmushcu** [comment]
> > Absolutely, i thought i should ask, if you're busy or something i thought i could be helpful. There is no inconvenience. As for the splitting issues, i guess these two issues could be solved with the same approach, so you should take up both. Sorry if my recent comment is a bit indiscreet.
> 
> if that's the case , then please go ahead with the issue because its true that i am a bit busy . Thanks for the help . and about your comments being indiscreet, i would say it was me who was being disrespectfull since the issue has been sitting for more than a month now so your comment was completely right on the mark . so please go ahead with the issue again sorry for my behavior

i feel like we've been missunderstood eachother, you should work on it if you'll have time and i will open a PR in a month if you haven't yet.

**Comment by shravan20** [comment]
> > Hi @dolmushcu #124 is a different feature implementation compared to this one. Both will have different approaches. We cannot go with the same approach.
> 
> Here is what i thought: In the file where the themes being specified (src/themes/themes.js), we could pass `bg_color` values directly. I mean right now `#` character is being added automaticly assuming every value that passed is hex in the layout file. However if we let people pass quote_color, bg_color... freely, they could be able to pass gradient color and image.
> 
> EXP: bg_color: "linear-gradient(to right, #0f2027, #203a43, #2c5364)" EXP: bg_color: "url('http://example.com/image.png')" EXP: bg_color: "#fff"
> 
> When i mention about same approach i was talking about something like this. What do you think? Does this approach have any drawback?

Sounds perfect
