### ISSUE TITLE
Gradient Design Background for the Quote Card 

### ISSUE THREAD

**Issue by shravan20** [shravan20/github-readme-quotes#124]
**Is your feature request related to a problem? Please describe.**
Implementation for the Github-Readme-Quotes for the Card

**Describe the solution you'd like**
Alternative background solution instead of current SOLID COLOUR option, where user passes gradient name, and corresponding quote background.

**Comment by Rispectech** [comment]
how about letting the user make custom color through gradient . we can take options for the user whether he/she wants a single colour or a gradient one and then take the values from the user which we can pass and then tweak the CSS 

for example the user select gradient and passer red to yellow :
             we can pass both red and yellow and then tweak linear gradient(red,yellow)

I can take up the issue if its okay with you

**Comment by shravan20** [comment]
Hi there!

Looks like a promising feature. We can have it implemented and you can accordingly raise the PR for the same. 
Thank you so much for the time! :)
