### ISSUE TITLE
Adding Product Upvote in ProductHunt in the React Application 

### ISSUE THREAD

**Issue by shravan20** [shravan20/github-readme-quotes#126]
**Is your feature request related to a problem? Please describe.**
Implementation of upvote button from Product Hunt for the React Application  

**Describe the solution you'd like**
Simple Upvote option for the User's to upvote our product/redirect to the [Product Hunt page](https://www.producthunt.com/posts/dynamic-github-profile-readme-quotes?utm_source=badge-featured&utm_medium=badge&utm_souce=badge-dynamic-github-profile-readme-quotes)

**Additional context**
You have an embedded option provided by the Product Hunt itself, you can use it as well
- [Product Hunt](https://www.producthunt.com/posts/dynamic-github-profile-readme-quotes?utm_source=badge-featured&utm_medium=badge&utm_souce=badge-dynamic-github-profile-readme-quotes)
- [Embedded Design](https://www.producthunt.com/posts/dynamic-github-profile-readme-quotes/embed)

**Comment by OlushesiToheeb** [comment]
I'd love to take this issue... @shravan20

**Comment by shravan20** [comment]
Greetings @OlushesiToheeb 
Feel free to raise a PR after the implementation! Thank you for picking up the issue!
Cheers!

**Comment by OlushesiToheeb** [comment]
@shravan20  where exactly am I doing this? and am I build project locally in `frontend/src` ?

**Comment by OlushesiToheeb** [comment]
and also steps in building it locally

**Comment by shravankb** [comment]
You supposed to add it in the frontend/src You can build and send the screenshot of the UI.
Ensure that you don't push the build. We have added that into `.gitignore`.
I hope that helps.

Cheers

**Comment by OlushesiToheeb** [comment]
Hi @shravankb kindly check this UI before pushing, is it okay on the header?
![image](https://user-images.githubusercontent.com/46800177/116610068-f66b3700-a8e9-11eb-8eb5-33ec1119bf0d.png)

**Comment by shravan20** [comment]
This looks good. Can we have the product hunt div first and then dark mode button?

**Comment by OlushesiToheeb** [comment]
Sure!

**Comment by OlushesiToheeb** [comment]
https://github.com/shravan20/github-readme-quotes/pull/136
