### ISSUE TITLE
[Refactoring] Move the assets files for React Application 

### ISSUE THREAD

**Issue by shravan20** [shravan20/github-readme-quotes#127]
**Is your feature request related to a problem? Please describe.**
Moving all the svg based files to assets folder rather keeping it in [/frontend/src/](https://github.com/shravan20/github-readme-quotes/tree/main/frontend/src)

**Describe the solution you'd like**
Create an assets folder [/frontend/src/assets] and add all the assets into same folder

**Comment by OlushesiToheeb** [comment]
I'll love to  take up this issue too.. @shravan20

**Comment by shravan20** [comment]
Hi @OlushesiToheeb, 

Please feel free to raise a PR after corresponding changes. 
Cheers!
