### ISSUE TITLE
Alignment of Zues template in Front-End

### ISSUE THREAD

**Issue by version0chiro** [shravan20/github-readme-quotes#128]
There is a certain unalignment and nonuniform size with the last template in the other layouts. This only occurs for Zues layout which makes it look a bit uneven.

Steps:
1. Open The front end website on full screen desktop and scroll down.
2. Use the react developer tool to check the size of template cards.

System Specification:

- Windows 10
- Monitor size: 1920x1080
- Browser Used: Brave

Screenshots:
![image](https://user-images.githubusercontent.com/56084650/116184457-6be5d480-a73d-11eb-950b-fba749b95875.png)

**Comment by shravan20** [comment]
Hi @version0chiro 
Are you willing to work on this issue?
