### ISSUE TITLE
[Feature Request] Github Action to deploy using Pipeline CI/CD

### ISSUE THREAD

**Issue by shravan20** [shravan20/github-readme-quotes#132]
**Is your feature request related to a problem? Please describe.**
GitHub Action to Deploy Application from the Github Directly to the Heroku

**Comment by theSatvik** [comment]
Hi @shravan20, can I work on this? I was learning GitHub actions, looking to work on one.

**Comment by shravan20** [comment]
Hi @theSatvik 

Thank you for your considering the project. You can take the liberty to give it a try in your fork and raise a final PR.

Your efforts counts. Thank you so much :)

**Comment by theSatvik** [comment]
Hi, @shravan20 Thank you, I have started working on this.

**Comment by geekyrajshri** [comment]
Hi @shravan20 
Can I take this up, if theSatvik is not working on this?

**Comment by shravan20** [comment]
I have for now completed this, by completely moving it to VERCEL and automating the process.

Thank you all for your active participation. Look forward for more active participation.

**Comment by shravan20** [comment]
Marking this as completed.
