### ISSUE TITLE
The page is not working and the renders are not loading on the profile 

### ISSUE THREAD

**Issue by version0chiro** [shravan20/github-readme-quotes#137]
**Describe the bug**
The server is down perhaps as nothing is being returned from the link and the page is also not working.
**To Reproduce**
Open the official website for the application or try to see your own GitHub quotes card

**Screenshots**

![image](https://user-images.githubusercontent.com/56084650/119555480-8900d800-bdbb-11eb-924e-00de3e0e59b3.png)

**Comment by shravankb** [comment]
Issue has been resolved..

**Comment by shravankb** [comment]
Thanks for raising the concern!

**Comment by saniales** [comment]
It happened again, please fix

**Comment by shravan20** [comment]
@version0chiro : We have migrated this successfully to custom cloud, please refer to: [34.168.217.81:3004](http://34.168.217.81:3004/)
