### ISSUE TITLE
Creation and implementation of SwaggerDocs

### ISSUE THREAD

**Issue by shravan20** [shravan20/github-readme-quotes#151]
**Is your feature request related to a problem? Please describe.**
Implementation of SwaggerDocs for maintaining developer's reference documentation.

**Describe the solution you'd like**
Use `swagger-ui-express` and `swagger-jsdoc` 
For detailed implementation plan, refer this [article](https://blog.logrocket.com/documenting-your-express-api-with-swagger/)
![](https://blog.logrocket.com/wp-content/uploads/2020/09/node-logo.png)

**Comment by SwarajBaral** [comment]
Hey @shravan20 I would love to take it up. Can you assign it to me ?

**Comment by shravan20** [comment]
Hi @SwarajBaral 

Thank you for the time! I will have this issue assigned to you.

**Comment by MightyFellow** [comment]
Hey @shravan20 

Can I contribute to this issue if it's still open ? I am a beginner

**Comment by shravan20** [comment]
Sure, please feel free to pick up this issue. 
Can i assign this issue to you?

**Comment by MightyFellow** [comment]
> Sure, please feel free to pick up this issue. Can i assign this issue to you?

Yes please. Thank you

**Comment by shravan20** [comment]
I've re-assigned it to you

**Comment by ghanvik** [comment]
Hello, if this is still open could I work on it? Maybe it could be split up if others are still working on it. I am a beginner at Swagger and documenting REST APIs.

**Comment by shravan20** [comment]
@ghanvik : Feel free to pick this up. Lmk if you are working on it. I will re-assign this to you

**Comment by ghanvik** [comment]
I'm trying to test the API calls using Postman but it looks like the service is not working. Is there a way to run it locally?

**Comment by ghanvik** [comment]
The Heroku app is working now, but I'm having trouble getting the app to start locally with the `npm start` command. If we want to create documentation like the [article](https://blog.logrocket.com/documenting-your-express-api-with-swagger/) describes, it seems like it requires the app to start locally. Can anyone provide instructions on how to run it locally?

Alternatively I could just write a .yaml file manually for Swagger.

Here is the error message I am getting
`C:\Users\[username]\github repos\github-readme-quotes\src\themes\themes.js:270`

`export default themes;`

`^^^^^^`

`SyntaxError: Unexpected token 'export'
    at wrapSafe (node:internal/modules/cjs/loader:999:16)
    at Module._compile (node:internal/modules/cjs/loader:1047:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1112:10)
    at Module.load (node:internal/modules/cjs/loader:948:32)
    at Function.Module._load (node:internal/modules/cjs/loader:789:14)
    at Module.require (node:internal/modules/cjs/loader:972:19)
    at require (node:internal/modules/cjs/helpers:88:18)
    at Object.<anonymous> (C:\Users\vikra\github repos\github-readme-quotes\src\api\controllers\quotesController.js:1:16)
    at Module._compile (node:internal/modules/cjs/loader:1083:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1112:10)`

**Comment by ghanvik** [comment]
Yes, this was resolved.
