### ISSUE TITLE
Heroku hosted doesn't work

### ISSUE THREAD

**Issue by ichal6** [shravan20/github-readme-quotes#185]
**Describe the bug**
Your page doesn't work:
[link](https://github-readme-quotes.herokuapp.com/)

**Screenshot**
![Screenshot](https://user-images.githubusercontent.com/53079655/165282250-3c9d6c2c-9882-4a26-825d-599b83019217.png)

**Additional context**
Maybe there is a reason?
[Heroku Security Notification](https://status.heroku.com/incidents/2413)
[Github blog](https://github.blog/2022-04-15-security-alert-stolen-oauth-user-tokens/)

**Comment by shravan20** [comment]
We are currently using free version of Heroku, hence causing 1 day's downtime in a week based on the usage.

**Comment by ichal6** [comment]
> We are currently using free version of Heroku, hence causing 1 day's downtime in a week based on the usage.

OK. Thanks for info.

**Comment by shravan20** [comment]
@ichal6 : We have migrated this successfully to custom cloud, please refer to: [34.168.217.81:3004](http://34.168.217.81:3004/)
