### ISSUE TITLE
Heroku hosting is not working

### ISSUE THREAD

**Issue by getlost01** [shravan20/github-readme-quotes#218]
Hey developer, your `https://github-readme-quotes.herokuapp.com/quote` is not working since Heroku has stopped its all free services, I request to change the hosting platform.

<img width="540" alt="Screenshot 2022-12-17 at 1 46 50 PM" src="https://user-images.githubusercontent.com/79409258/208232887-55a4bb1c-ca92-431c-ac1f-f84ab6c285ff.png">

Suggested platforms are:
- [vercel](https://vercel.com/)
- [Cyclic](https://www.cyclic.sh/)
- [Render](https://render.com/)

**Comment by shravan20** [comment]
@getlost01 : We have migrated this successfully to custom cloud, please refer to: [34.168.217.81:3004](http://34.168.217.81:3004/)
