### ISSUE TITLE
feat: Quote of the day Widget Feature 

### ISSUE THREAD

**Issue by shravan20** [shravan20/github-readme-quotes#236]
**Is your feature request related to a problem? Please describe.**
Currently we support feature to generate dynamic quotes, but not static quotes

**Describe the solution you'd like**
This feature would allow to provide static quotes on daily basis. This quote for a profile would change on per day basis.

**Comment by ayan-joshi** [comment]
Can u assign this issue to me , I would like to work on it @shravan20

**Comment by shravan20** [comment]
Assigned to you @ayan-joshi

**Comment by 4nshuman** [comment]
hello @shravan20, was this issue fixed or is it still open to work on ?

**Comment by shravan20** [comment]
> hello @shravan20, was this issue fixed or is it still open to work on ?

This issue is open for development

**Comment by 4nshuman** [comment]
Thanks for the confirmation @shravan20, I’d love to take it up, could you please assign me to the task.

**Comment by shravan20** [comment]
Moving it to @4nshuman for dev

**Comment by 4nshuman** [comment]
Hello @shravan20 , I've created a PR for this change, please take a look and review.
https://github.com/shravan20/github-readme-quotes/pull/308
