### ISSUE TITLE
Quotes badge is broken 

### ISSUE THREAD

**Issue by manzil-infinity180** [shravan20/github-readme-quotes#245]
<img width="1680" alt="Screenshot 2023-09-27 at 3 15 20 PM" src="https://github.com/shravan20/github-readme-quotes/assets/119070053/0292743b-7c8d-4670-a66f-08d60e373f1d">

**Comment by shravan20** [comment]
@manzil-infinity180: Do you want to pick it up to add cacheable images and replace these url with new urls?

**Comment by shravan20** [comment]
@manzil-infinity180: Lmk if you would want to pick it up, I can guide you with the changes required for it which would be minor change along with how this change would work as well. 

Thank you for raising the issue and taking a look at the project. Your time matters. :D

**Comment by manzil-infinity180** [comment]
assign it to me , can i work on this issue under **hacktoberfest**

**Comment by shravan20** [comment]
@manzil-infinity180: Sure, you can take this up. Fixing the cache issue, is already being taken care by @ashishk1331 in issue:
https://github.com/shravan20/github-readme-quotes/issues/156.

Can you take up the task to update the document accordingly in the places where URLs are broken after the fix by Ashish?

**Comment by fathomer** [comment]
Hi @manzil-infinity180: Are you still working on this?

**Comment by shravan20** [comment]
Hi folks,

As part of clean up and migration, moved it to Vercel meanwhile considering minor issues. As part of the process, fixed this issue as well. Moving this to closed, reopen if required.

Thank you for your participation and time. 🔥

**Comment by shravan20** [comment]
Marking as closed with #288 as resolution
