### ISSUE TITLE
bug: UI Dashboard drop down issue

### ISSUE THREAD

**Issue by shravan20** [shravan20/github-readme-quotes#253]
**_Description:_**

This issue relates to template selection in the quote card. In the UI, the themes selected are not getting reflected since recent feature to add color background and font color is overriding the actual defined templates

![image](https://github.com/shravan20/github-readme-quotes/assets/47430686/81a28a1d-4819-458e-879c-c7054df0ebc1)

Looping in @GRenziITDM for better context & review

**Comment by RahulSoni2532** [comment]
I can fix this issue please assign this to me @shravan20

**Comment by shravan20** [comment]
@RahulSoni2532 : Please take this issue. Thank you so much for your contribution 💫💫

**Comment by RahulSoni2532** [comment]
hey getting an issue that how can i run it on local host

**Comment by RahulSoni2532** [comment]
are you talking about this dropdown issue

![Screenshot 2023-10-05 011312](https://github.com/shravan20/github-readme-quotes/assets/146342894/739735a8-f2d1-4caf-b023-b0d9e6bfc73a)

**Comment by shravan20** [comment]
No.

Steps to reproduce the issue.

- Select some random background and font color.
- Now select any theme. See if theme is getting reflected or not.

**Comment by GRenziITDM** [comment]
Hi @shravan20 my bad, it seems I didn't test enough for regressions. @RahulSoni2532 if you need help text me on discord "g.renzi", thank you and have a good day 😄

**Comment by shravan20** [comment]
@GRenziITDM: That is totally fine, this should be good issue to work. I missed this during my review as well.

**Comment by shravan20** [comment]
@GRenziITDM @RahulSoni2532: Feel free to join the [discord channel](https://discord.gg/2vGDECMhZ8)

**Comment by shravan20** [comment]
@GRenziITDM @RahulSoni2532: Are you guys still working on this? Do you need any help here?

**Comment by PavanVarma474** [comment]
@shravan20 I wanted to work on this

**Comment by shravan20** [comment]
> @shravan20 I wanted to work on this
> 

@PavanVarma474 This is open to pick, shall I re assign this to you.

**Comment by PavanVarma474** [comment]
> > @shravan20 I wanted to work on this
> 
> @PavanVarma474 This is open to pick, shall I re assign this to you.

Yes, i want to work on this

**Comment by PavanVarma474** [comment]
@shravan20 i have a doubt, i could run the react frontned by going to frontned folder and running npm start. But aslo by runnig nodemon server.js it is also opening similar environment. I resolved the issue from  react frontend side. But why again a separate server environemnt? The changes i made on react side are not getting reflected when i run from server side(nodemon server.js). Should i also deal with server side separately. Why two when each is able to have a complete application.

**Comment by 4nshuman** [comment]
Hey @shravan20, I'd like to pick this issue up.
Please assign.

**Comment by shravan20** [comment]
@4nshuman Assigning this to you

**Comment by RiTiKa-ShIsHoDiA** [comment]
hii @shravan20  this issue is open , i want to work on it

**Comment by 4nshuman** [comment]
Hi @shravan20, have raised a PR for this issue.
Please take a look and let me know in case of any review comments.

**Comment by shravan20** [comment]
**_Marking this as resolved_**

@4nshuman Thank you so much for you contribution <3
