### ISSUE TITLE
chore: move all promises syntactic to async/await

### ISSUE THREAD

**Issue by shravan20** [shravan20/github-readme-quotes#262]
# Task
Refactor the codebase to utilize async/await syntax instead of promises for improved readability and maintainability.

# Details
Currently, the codebase extensively uses promises for asynchronous operations. Converting these to utilize async/await syntax will enhance the codebase in the following ways:

- Readability: Async/await syntax provides a more intuitive and synchronous-like flow, making the code easier to read and understand.
- Error Handling: async/await allows for more natural error handling using try/catch blocks, improving error traceability.
- Simplified Logic: Converting promise chains to async functions simplifies the control flow and reduces the need for nested .then() calls.

# Steps to Accomplish
- Identify all occurrences of promise-based syntax in the codebase.
- Replace these with appropriate async/await usage.
- Ensure that error handling is appropriately adjusted using try/catch blocks.
- Thoroughly test the refactored code to ensure functionality and performance are maintained.

# Additional Information
- Ensure to maintain code functionality and avoid introducing regressions during the refactoring process.
- Pay attention to error handling and propagate errors appropriately.
- Consider documenting the changes made and update relevant documentation if needed.

**Comment by krushn-a** [comment]
Hey @shravan20 , Can i work on this issue?

**Comment by shravan20** [comment]
Sure @krushn-a assigning this to you

**Comment by krushn-a** [comment]
Hi I have made the required changes but facing bit difficulty in deploying it in my environment.
So I have been using the code `npm run start-dev` to run the local host.
But whenever I made any changes in codebase the localhost doesn't get updated.
Can you please help me to get over it.

**Comment by fathomer** [comment]
@krushn-a Hey, do you need a live reload of the server whenever you make a change locally? I think by default, node does not do it.
Check out https://github.com/remy/nodemon which achieves this.  `nodemon --exec npm run start-dev`

**Comment by SaurabhXRT** [comment]
Hey..if this issue is not fixed yet then i want to work on it..please assign me

**Comment by shravan20** [comment]
@SaurabhXRT : Please take it forward

**Comment by SaurabhXRT** [comment]
Hey @shravan20 ..i have fixed the issue and created a pr please have a look

**Comment by shravan20** [comment]
Closing this as fixed
