### ISSUE TITLE
Add Customizable Border Color Option to Default Layout

### ISSUE THREAD

**Issue by marceloams** [shravan20/github-readme-quotes#332]
**Feature Request: Customizable Border Color for Default Layout**

**Is your feature request related to a problem? Please describe.**  
It would be useful to have a configurable option to set the border color for the default layout, allowing for greater flexibility in design.

**Describe the solution you'd like**  
Introduce a `borderColor` parameter to specify the border color for the default layout. If `borderColor` is not provided, the border will fall back to the current default color.

Example usage:  
`&borderColor=orange`

**Mockup for Reference**  
![Border Color Example](https://github.com/user-attachments/assets/8915da6c-895f-47c1-8ba8-515da6cc651d)

**Additional Context**  
This feature would improve customization options, especially for cases where a different visual style is desired without modifying the entire layout theme.

**Request for Assignment**  
I would like to work on this feature and submit a pull request for it. Please assign this issue to me if approved.

**Comment by Lemeri123** [comment]
is this issue still open?? @marceloams

**Comment by marceloams** [comment]
Hi @Lemeri123! Thanks for checking in. I've already submitted a pull request with the feature and am currently awaiting review/approval from @shravan20.
