### ISSUE TITLE
[Feature Request] Custom Quotes

### ISSUE THREAD

**Issue by ShubhKotnala** [shravan20/github-readme-quotes#78]
**Problem Statement**
I'm excited by the fact that I would be able to add dynamic quotes to my GitHub read-me page, but these quotes would be always random. The quotes that would be generated by a specific category or from a list of quotes would be highly useful as that would meet the requirement to clearly give dynamic quotes based on my profile, ex: Designer, Developer, etc. 

**Possible Solution**
A file in the GitHub profile repository that contains a list of data that would be used to get the quotes data from, so that always predictable, but random quotes appear on the read-me.

**Additional context**
Let's say I have a read-me page and I want to have random quotes but from a certain set of quotes. I would make a file from a template and enter the quotes, then I would get the quotes to my read-me page from this file. In this way I'm sure what my profile viewers would see.

**Comment by nishantpersonal** [comment]
Hi @ShubhKotnala ,
Your feature request has been accepted.Please proceed ahead.
Make sure to go through [contributing.md](https://github.com/shravan20/github-readme-quotes/blob/main/CONTRIBUTING.md) before raising the PR.
