### ISSUE TITLE
[Preview Quotes and Generate URL] 

### ISSUE THREAD

**Issue by shravan20** [shravan20/github-readme-quotes#83]
**Is your feature request related to a problem? Please describe.**
Create User Interface to preview different possible template combinations and get the generated URL for the same.
 
**Describe the solution you'd like**
Pending

**Comment by ShubhKotnala** [comment]
**Possible Solution**
A simple react app that would preview the combinations of multiple template combination would work here. React app would make it dynamic, making it to work without reloading the page.
