### ISSUE TITLE
[BUG] Inconsistent SVG size

### ISSUE THREAD

**Issue by ShubhKotnala** [shravan20/github-readme-quotes#87]
**Describe the bug**
The `svg` image returned from the server is of a static size `700x300` which makes it difficult to align properly with the content since the extra space is filled with `transparent` background, which makes that space unusable.

**To Reproduce**
1. Generate any quote with any layout. 
2. Check the size of the image, and the actual content size of the image. 

**Expected behavior**
`svg` size is expected to be the same as the necessary content. 

**Screenshots**
![image](https://user-images.githubusercontent.com/31727459/100976070-06623300-3565-11eb-800c-23c0dcdf157b.png)

**Comment by shravan20** [comment]
Issues solved #90 
Thank you for the raising the issue.
